
# It was adapted by Candace Savonen for the OTTR_template https://github.com/jhudsl/OTTR_Template.

# This code was adapted by Carrie Wright to enable automated rendering of the site associated with this repository

name: Render html

# Controls when the action will run. Triggers the workflow on push
# events only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**.Rmd'
      - styles.css
      - _site.yml
      - resources/images/*.png
      - resources/images/favicon.ico

jobs:
  yaml-check:
    name: Load user automation choices
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # Use the yaml-env-action action.
      - name: Load environment from YAML
        uses: doughepi/yaml-env-action@v1.0.0
        with:
            files: config_automation.yml # Pass a space-separated list of configuration files. Rightmost files take precedence.

    outputs:
      rendering_docker_image: "${{ env.RENDERING_DOCKER_IMAGE }}"

  # This workflow contains a single job called "build-all"
  render-main:
    needs: yaml-check
    runs-on: ubuntu-latest
    container:
      image: ${{needs.yaml-check.outputs.rendering_docker_image}}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v4
        with:
          # get the full repo
          fetch-depth: 0
          # use github PAT
          token: ${{ secrets.GH_PAT }}

      # Set up / install jq so that json credentials can be read in
      - name: Install jq
        uses: dcarbone/install-jq-action@v2.1.0

      # We want a fresh run of the renders each time - so first delete old html files
      - name: Delete old *.html
        run: Rscript -e "rmarkdown::clean_site(preview = FALSE)"

       #Now we want to get data from googlesheets and make it available to all of the Rmds and render all the html files from the Rmd files
       # Loqui data (3 columns: date_time, video_duration, email)
       - name: get loqui data
         id: 'get_sheet_loqui'
         uses: jroehl/gsheet.action@v2.1.1
         with:
           spreadsheetId: '1G_HTU-bv2k5txExP8EH3ScUfGqtW1P3syThD84Z-g9k'
           commands: | #list of commands, specified as a valid JSON string
             [
               { "command": "getWorksheet", "args": { "worksheetTitle": "Sheet1" }},
               { "command": "getData", "args": { "range": "'Sheet1'!A:C" } }
             ]
         env:
           GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
           GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}

       # Loqui supplemental data (1 column only: date_time
       - name: get loqui data supplemental
         id: 'get_sheet_loqui_supp'
         uses: jroehl/gsheet.action@v2.1.1
         with:
           spreadsheetId: '1G_HTU-bv2k5txExP8EH3ScUfGqtW1P3syThD84Z-g9k'
           commands: | #list of commands, specified as a valid JSON string
             [
               { "command": "getWorksheet", "args": { "worksheetTitle": "FromLogsAndDan" }},
               { "command": "getData", "args": { "range": "'FromLogsAndDan'!A1:A135" } }
             ]
         env:
           GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
           GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}

      # course counts for leanpub and coursera
      - name: get course counts for leanpub and coursera
        id: 'get_sheet_courses'
        uses: jroehl/gsheet.action@v2.1.1
        with:
          spreadsheetId: '1-8vox2LzkVKzhmSFXCWjwt3jFtK-wHibRAq2fqbxEyo'
          commands: | #list of commands, specified as a valid JSON string
            [
              { "command": "getWorksheet", "args": { "worksheetTitle": "Course_data" }},
              { "command": "getData", "args": { "range": "'Course_data'!A1:I14" }}
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}

      # Now we want to render all the html files from the Rmd files
      - name: Run render html
        id: site
        env:
          # the output of the action above!
          RESULTS_LOQ: ${{ steps.get_sheet_loqui.outputs.results }}
          RESULTS_LOQ_SUPP: ${{ steps.get_sheet_loqui_supp.outputs.results }}
          RESULTS_COURSES: ${{ steps.get_sheet_courses.outputs.results }}
        run: |
          Rscript --vanilla "resources/render.R" --data_in_loq "$RESULTS_LOQ" \
                                                 --data_in_loq_supp "$RESULTS_LOQ_SUPP" \
                                                 --data_in_courses "$RESULTS_COURSES"

      # This checks on the steps before it and makes sure that they completed.
      # If the renders didn't complete we don't want to commit the file changes
      - name: Check on render steps
        if: steps.site.outcome != 'success'
        run: |
          echo site status ${{steps.site.outcome}}
          exit 1

# Commit the rendered site files - html files and site_libs files
# The git reset step will remove any other files created in this workflow, such as API keys
      - name: Commit rendered site files
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add --force docs/*
          git commit -m 'Render site' || echo "No changes to commit"
          git reset --hard HEAD
          git pull --rebase --allow-unrelated-histories --strategy-option=ours
          git push origin main || echo "No changes to push"
